
organization: testing_redocly

extends:
  - recommended

apis:
  core@v2:
    root: ./openapi/openapi.yaml
    rules:
      no-ambiguous-paths: error
  external@v1:
    root: ./openapi/external.yaml
    labels:
      - external
    features.openapi:
      hideLogo: true

features.openapi:
  schemaExpansionLevel: 2
  generateCodeSamples:
    languages:
      - lang: Javascript
      - lang: Python
